In [141]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

EDA

In [142]:
data = "/Users/leona/OneDrive/Documentos/GitHub/Machine-learning-studies-2/ensemble/random_forest/exercise/BRAZIL_CITIES.csv"

In [143]:
df = pd.read_csv(data, sep=';', decimal=',')

In [144]:
df.head()

,CITY,STATE,CAPITAL,IBGE_RES_POP,IBGE_RES_POP_BRAS,IBGE_RES_POP_ESTR,IBGE_DU,IBGE_DU_URBAN,IBGE_DU_RURAL,IBGE_POP,IBGE_1,IBGE_1-4,IBGE_5-9,IBGE_10-14,IBGE_15-59,IBGE_60+,IBGE_PLANTED_AREA,IBGE_CROP_PRODUCTION_$,IDHM Ranking 2010,IDHM,IDHM_Renda,IDHM_Longevidade,IDHM_Educacao,LONG,LAT,ALT,PAY_TV,FIXED_PHONES,AREA,REGIAO_TUR,CATEGORIA_TUR,ESTIMATED_POP,RURAL_URBAN,GVA_AGROPEC,GVA_INDUSTRY,GVA_SERVICES,GVA_PUBLIC,GVA_TOTAL,TAXES,GDP,POP_GDP,GDP_CAPITA,GVA_MAIN,MUN_EXPENDIT,COMP_TOT,COMP_A,COMP_B,COMP_C,COMP_D,COMP_E,COMP_F,COMP_G,COMP_H,COMP_I,COMP_J,COMP_K,COMP_L,COMP_M,COMP_N,COMP_O,COMP_P,COMP_Q,COMP_R,COMP_S,COMP_T,COMP_U,HOTELS,BEDS,Pr_Agencies,Pu_Agencies,Pr_Bank,Pu_Bank,Pr_Assets,Pu_Assets,Cars,Motorcycles,Wheeled_tractor,UBER,MAC,WAL-MART,POST_OFFICES
0,Abadia De Goiás,GO,0,6876.0,6876.0,0.0,2137.0,1546.0,591.0,5300.0,69.0,318.0,438.0,517.0,3542.0,416.0,319.0,1843.0,1689.0,0.708,0.687,0.83,0.622,-49.44054783,-16.75881189,893.6,360.0,842.0,147.26,NaN,NaN,8583.0,Urbano,6.2,27991.25,74750.32,36915.04,145857.6,20554.2,166.41,8053.0,20664.57,Demais serviços,28227691.0,284.0,5.0,1.0,56.0,0.0,2.0,29.0,110.0,26.0,4.0,5.0,0.0,2.0,10.0,12.0,4.0,6.0,6.0,1.0,5.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2158.0,1246.0,0.0,NaN,NaN,NaN,1.0
1,Abadia Dos Dourados,MG,0,6704.0,6704.0,0.0,2328.0,1481.0,847.0,4154.0,38.0,207.0,260.0,351.0,2709.0,589.0,4479.0,18017.0,2207.0,0.69,0.693,0.839,0.563,-47.39683244,-18.48756496,753.12,77.0,296.0,881.06,Caminhos Do Cerrado,D,6972.0,Rural Adjacente,50524.57,25917.7,62689.23,28083.79,167215.28,12873.5,180.09,7037.0,25591.7,Demais serviços,17909274.0,476.0,6.0,6.0,30.0,1.0,2.0,34.0,190.0,70.0,28.0,11.0,0.0,4.0,15.0,29.0,2.0,9.0,14.0,6.0,19.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2227.0,1142.0,0.0,NaN,NaN,NaN,1.0
2,Abadiânia,GO,0,15757.0,15609.0,148.0,4655.0,3233.0,1422.0,10656.0,139.0,650.0,894.0,1087.0,6896.0,990.0,10307.0,33085.0,2202.0,0.69,0.671,0.841,0.579,-48.71881214,-16.18267186,1017.55,227.0,720.0,"1,045.13",Região Turística Do Ouro E Cristais,C,19614.0,Rural Adjacente,42.84,16728.3,138198.58,63396.2,261161.91,26822.58,287984.49,18427.0,15628.4,Demais serviços,37513019.0,288.0,5.0,9.0,26.0,0.0,2.0,7.0,117.0,12.0,57.0,2.0,1.0,0.0,7.0,15.0,3.0,11.0,5.0,1.0,8.0,0.0,0.0,1.0,34.0,1.0,1.0,1.0,1.0,33724584.0,67091904.0,2838.0,1426.0,0.0,NaN,NaN,NaN,3.0
3,Abaeté,MG,0,22690.0,22690.0,0.0,7694.0,6667.0,1027.0,18464.0,176.0,856.0,1233.0,1539.0,11979.0,2681.0,1862.0,7502.0,1994.0,0.698,0.72,0.848,0.556,-45.44619142,-19.15584769,644.74,1230.0,1716.0,"1,817.07",Lago De Três Marias,D,23223.0,Urbano,113824.6,31002.62,172.33,86081.41,403241.27,26994.09,430235.36,23574.0,18250.42,Demais serviços,NaN,621.0,18.0,1.0,40.0,0.0,1.0,20.0,303.0,62.0,30.0,9.0,6.0,4.0,28.0,27.0,2.0,15.0,19.0,9.0,27.0,0.0,0.0,NaN,NaN,2.0,2.0,2.0,2.0,44974716.0,371922572.0,6928.0,2953.0,0.0,NaN,NaN,NaN,4.0
4,Abaetetuba,PA,0,141100.0,141040.0,60.0,31061.0,19057.0,12004.0,82956.0,1354.0,5567.0,7618.0,8905.0,53516.0,5996.0,25200.0,700872.0,3530.0,0.628,0.579,0.798,0.537,-48.88440382,-1.723469863,10.12,3389.0,1218.0,"1,610.65",Araguaia-Tocantins,D,156292.0,Urbano,140463.72,58610,468128.69,486872.4,1154074.81,95180.48,1249255.29,151934.0,8222.36,"Administração, defesa, educação e saúde públic...",NaN,931.0,4.0,2.0,43.0,0.0,1.0,27.0,500.0,16.0,31.0,6.0,1.0,1.0,22.0,16.0,2.0,155.0,33.0,15.0,56.0,0.0,0.0,NaN,NaN,2.0,4.0,2.0,4.0,76181384.0,800078483.0,5277.0,25661.0,0.0,NaN,NaN,NaN,2.0

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5573 entries, 0 to 5572
Data columns (total 81 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CITY                    5573 non-null   object
 1   STATE                   5573 non-null   object
 2   CAPITAL                 5573 non-null   int64
 3   IBGE_RES_POP            5565 non-null   float64
 4   IBGE_RES_POP_BRAS       5565 non-null   float64
 5   IBGE_RES_POP_ESTR       5565 non-null   float64
 6   IBGE_DU                 5563 non-null   float64
 7   IBGE_DU_URBAN           5563 non-null   float64
 8   IBGE_DU_RURAL           5492 non-null   float64
 9   IBGE_POP                5565 non-null   float64
 10  IBGE_1                  5565 non-null   float64
 11  IBGE_1-4                5565 non-null   float64
 12  IBGE_5-9                5565 non-null   float64
 13  IBGE_10-14              5565 non-null   float64
 14  IBGE_15-59              5565 non-null   float64
 15  IBGE_60+                5565 non-null   float64
 16  IBGE_PLANTED_AREA       5570 non-null   float64
 17  IBGE_CROP_PRODUCTION_$  5570 non-null   float64
 18  IDHM Ranking 2010       5565 non-null   float64
 19  IDHM                    5565 non-null   object
 20  IDHM_Renda              5565 non-null   object
 21  IDHM_Longevidade        5565 non-null   object
 22  IDHM_Educacao           5565 non-null   object
 23  LONG                    5564 non-null   object
 24  LAT                     5564 non-null   object
 25  ALT                     5564 non-null   object
 26  PAY_TV                  5570 non-null   float64
 27  FIXED_PHONES            5570 non-null   float64
 28  AREA                    5570 non-null   object
 29  REGIAO_TUR              3285 non-null   object
 30  CATEGORIA_TUR           3285 non-null   object
 31  ESTIMATED_POP           5570 non-null   float64
 32  RURAL_URBAN             5570 non-null   object
 33  GVA_AGROPEC             5570 non-null   object
 34  GVA_INDUSTRY            5570 non-null   object
 35  GVA_SERVICES            5570 non-null   object
 36  GVA_PUBLIC              5570 non-null   object
 37   GVA_TOTAL              5570 non-null   object
 38  TAXES                   5570 non-null   object
 39  GDP                     5570 non-null   object
 40  POP_GDP                 5570 non-null   float64
 41  GDP_CAPITA              5570 non-null   object
 42  GVA_MAIN                5570 non-null   object
 43  MUN_EXPENDIT            4081 non-null   float64
 44  COMP_TOT                5570 non-null   float64
 45  COMP_A                  5570 non-null   float64
 46  COMP_B                  5570 non-null   float64
 47  COMP_C                  5570 non-null   float64
 48  COMP_D                  5570 non-null   float64
 49  COMP_E                  5570 non-null   float64
 50  COMP_F                  5570 non-null   float64
 51  COMP_G                  5570 non-null   float64
 52  COMP_H                  5570 non-null   float64
 53  COMP_I                  5570 non-null   float64
 54  COMP_J                  5570 non-null   float64
 55  COMP_K                  5570 non-null   float64
 56  COMP_L                  5570 non-null   float64
 57  COMP_M                  5570 non-null   float64
 58  COMP_N                  5570 non-null   float64
 59  COMP_O                  5570 non-null   float64
 60  COMP_P                  5570 non-null   float64
 61  COMP_Q                  5570 non-null   float64
 62  COMP_R                  5570 non-null   float64
 63  COMP_S                  5570 non-null   float64
 64  COMP_T                  5570 non-null   float64
 65  COMP_U                  5570 non-null   float64
 66  HOTELS                  887 non-null    float64
 67  BEDS                    887 non-null    float64
 68  Pr_Agencies             3342 non-null   float64
 69  Pu_Agencies             3342 non-null   float64
 70  Pr_Bank                 3342 non-null   float64
 71  Pu_Bank                 3342 non-null   float64
 72  Pr_Assets               3342 non-null   float64
 73  Pu_Assets               3342 non-null   float64
 74  Cars                    5562 non-null   float64
 75  Motorcycles             5562 non-null   float64
 76  Wheeled_tractor         5562 non-null   float64
 77  UBER                    125 non-null    float64
 78  MAC                     166 non-null    float64
 79  WAL-MART                102 non-null    float64
 80  POST_OFFICES            5453 non-null   float64
dtypes: float64(58), int64(1), object(22)
memory usage: 3.4+ MB

In [146]:
df.drop(['CITY', 'IDHM Ranking 2010', 'IDHM_Renda', 'IDHM_Longevidade', 'IDHM_Educacao', 'LONG', 'LAT', 'GVA_MAIN', 'REGIAO_TUR', 'MUN_EXPENDIT', 'HOTELS', 'BEDS', 'Pr_Agencies', 'Pu_Agencies', 'Pr_Bank', 'Pu_Bank', 'Pr_Assets', 'Pu_Assets','UBER','MAC','WAL-MART'], axis=1, inplace=True)

In [147]:
df['CATEGORIA_TUR'].value_counts()

CATEGORIA_TUR
D    1892
E     653
C     521
B     168
A      51
Name: count, dtype: int64

In [148]:
df.isna().sum() / len(df) * 100

STATE                      0.000000
CAPITAL                    0.000000
IBGE_RES_POP               0.143549
IBGE_RES_POP_BRAS          0.143549
IBGE_RES_POP_ESTR          0.143549
IBGE_DU                    0.179437
IBGE_DU_URBAN              0.179437
IBGE_DU_RURAL              1.453436
IBGE_POP                   0.143549
IBGE_1                     0.143549
IBGE_1-4                   0.143549
IBGE_5-9                   0.143549
IBGE_10-14                 0.143549
IBGE_15-59                 0.143549
IBGE_60+                   0.143549
IBGE_PLANTED_AREA          0.053831
IBGE_CROP_PRODUCTION_$     0.053831
IDHM                       0.143549
ALT                        0.161493
PAY_TV                     0.053831
FIXED_PHONES               0.053831
AREA                       0.053831
CATEGORIA_TUR             41.055087
ESTIMATED_POP              0.053831
RURAL_URBAN                0.053831
GVA_AGROPEC                0.053831
GVA_INDUSTRY               0.053831
GVA_SERVICES               0.053831
GVA_PUBLIC                 0.053831
 GVA_TOTAL                 0.053831
TAXES                      0.053831
GDP                        0.053831
POP_GDP                    0.053831
GDP_CAPITA                 0.053831
COMP_TOT                   0.053831
COMP_A                     0.053831
COMP_B                     0.053831
COMP_C                     0.053831
COMP_D                     0.053831
COMP_E                     0.053831
COMP_F                     0.053831
COMP_G                     0.053831
COMP_H                     0.053831
COMP_I                     0.053831
COMP_J                     0.053831
COMP_K                     0.053831
COMP_L                     0.053831
COMP_M                     0.053831
COMP_N                     0.053831
COMP_O                     0.053831
COMP_P                     0.053831
COMP_Q                     0.053831
COMP_R                     0.053831
COMP_S                     0.053831
COMP_T                     0.053831
COMP_U                     0.053831
Cars                       0.197380
Motorcycles                0.197380
Wheeled_tractor            0.197380
POST_OFFICES               2.153239
dtype: float64

In [149]:
for i in df.columns:
    percent = df[i].isna().sum()/len(df)*100
    if percent < 40:
        df.dropna(subset=i, inplace=True)

In [150]:
df.shape

(5368, 60)

In [151]:
encode_state = pd.get_dummies(df['STATE'])
encode_state = encode_state.astype(int)
df = pd.concat([df, encode_state], axis=1)

In [152]:
encode_ru = pd.get_dummies(df['RURAL_URBAN'])
encode_ru = encode_ru.astype(int)
df = pd.concat([df, encode_ru], axis=1)

In [153]:
df.drop(columns=['RURAL_URBAN', 'STATE'], axis=1, inplace=True)

In [154]:
df.head()

,CAPITAL,IBGE_RES_POP,IBGE_RES_POP_BRAS,IBGE_RES_POP_ESTR,IBGE_DU,IBGE_DU_URBAN,IBGE_DU_RURAL,IBGE_POP,IBGE_1,IBGE_1-4,IBGE_5-9,IBGE_10-14,IBGE_15-59,IBGE_60+,IBGE_PLANTED_AREA,IBGE_CROP_PRODUCTION_$,IDHM,ALT,PAY_TV,FIXED_PHONES,AREA,CATEGORIA_TUR,ESTIMATED_POP,GVA_AGROPEC,GVA_INDUSTRY,GVA_SERVICES,GVA_PUBLIC,GVA_TOTAL,TAXES,GDP,POP_GDP,GDP_CAPITA,COMP_TOT,COMP_A,COMP_B,COMP_C,COMP_D,COMP_E,COMP_F,COMP_G,COMP_H,COMP_I,COMP_J,COMP_K,COMP_L,COMP_M,COMP_N,COMP_O,COMP_P,COMP_Q,COMP_R,COMP_S,COMP_T,COMP_U,Cars,Motorcycles,Wheeled_tractor,POST_OFFICES,AC,AL,AM,AP,BA,CE,DF,ES,GO,MA,MG,MS,MT,PA,PB,PE,PI,PR,RJ,RN,RO,RR,RS,SC,SE,SP,TO,Intermediário Adjacente,Intermediário Remoto,Rural Adjacente,Rural Remoto,Urbano
0,0,6876.0,6876.0,0.0,2137.0,1546.0,591.0,5300.0,69.0,318.0,438.0,517.0,3542.0,416.0,319.0,1843.0,0.708,893.6,360.0,842.0,147.26,NaN,8583.0,6.2,27991.25,74750.32,36915.04,145857.6,20554.2,166.41,8053.0,20664.57,284.0,5.0,1.0,56.0,0.0,2.0,29.0,110.0,26.0,4.0,5.0,0.0,2.0,10.0,12.0,4.0,6.0,6.0,1.0,5.0,0.0,0.0,2158.0,1246.0,0.0,1.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,0,6704.0,6704.0,0.0,2328.0,1481.0,847.0,4154.0,38.0,207.0,260.0,351.0,2709.0,589.0,4479.0,18017.0,0.69,753.12,77.0,296.0,881.06,D,6972.0,50524.57,25917.7,62689.23,28083.79,167215.28,12873.5,180.09,7037.0,25591.7,476.0,6.0,6.0,30.0,1.0,2.0,34.0,190.0,70.0,28.0,11.0,0.0,4.0,15.0,29.0,2.0,9.0,14.0,6.0,19.0,0.0,0.0,2227.0,1142.0,0.0,1.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,0,15757.0,15609.0,148.0,4655.0,3233.0,1422.0,10656.0,139.0,650.0,894.0,1087.0,6896.0,990.0,10307.0,33085.0,0.69,1017.55,227.0,720.0,"1,045.13",C,19614.0,42.84,16728.3,138198.58,63396.2,261161.91,26822.58,287984.49,18427.0,15628.4,288.0,5.0,9.0,26.0,0.0,2.0,7.0,117.0,12.0,57.0,2.0,1.0,0.0,7.0,15.0,3.0,11.0,5.0,1.0,8.0,0.0,0.0,2838.0,1426.0,0.0,3.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,0,22690.0,22690.0,0.0,7694.0,6667.0,1027.0,18464.0,176.0,856.0,1233.0,1539.0,11979.0,2681.0,1862.0,7502.0,0.698,644.74,1230.0,1716.0,"1,817.07",D,23223.0,113824.6,31002.62,172.33,86081.41,403241.27,26994.09,430235.36,23574.0,18250.42,621.0,18.0,1.0,40.0,0.0,1.0,20.0,303.0,62.0,30.0,9.0,6.0,4.0,28.0,27.0,2.0,15.0,19.0,9.0,27.0,0.0,0.0,6928.0,2953.0,0.0,4.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,0,141100.0,141040.0,60.0,31061.0,19057.0,12004.0,82956.0,1354.0,5567.0,7618.0,8905.0,53516.0,5996.0,25200.0,700872.0,0.628,10.12,3389.0,1218.0,"1,610.65",D,156292.0,140463.72,58610,468128.69,486872.4,1154074.81,95180.48,1249255.29,151934.0,8222.36,931.0,4.0,2.0,43.0,0.0,1.0,27.0,500.0,16.0,31.0,6.0,1.0,1.0,22.0,16.0,2.0,155.0,33.0,15.0,56.0,0.0,0.0,5277.0,25661.0,0.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [155]:
x_train = df[df['CATEGORIA_TUR'].notnull()]
x_train.drop('CATEGORIA_TUR', axis=1, inplace=True)
y_train = df[df['CATEGORIA_TUR'].notnull()]['CATEGORIA_TUR']
x_test = df[df['CATEGORIA_TUR'].isnull()]
x_test.drop('CATEGORIA_TUR', axis=1, inplace=True)
y_test = df[df['CATEGORIA_TUR'].isnull()]['CATEGORIA_TUR']

C:\Users\leona\AppData\Local\Temp\ipykernel_5320\2399666185.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train.drop('CATEGORIA_TUR', axis=1, inplace=True)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\2399666185.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test.drop('CATEGORIA_TUR', axis=1, inplace=True)

In [156]:
for i in x_train.columns:
    if x_train[i].dtype == object:
        print(i)
        x_train[i] = x_train[i].str.replace(',', '')
        x_train[i] = x_train[i].astype(float)
for i in x_test.columns:
    if x_test[i].dtype == object:
        print(i)
        x_test[i] = x_test[i].str.replace(',', '')
        x_test[i] = x_test[i].astype(float)

IDHM
ALT
AREA
GVA_AGROPEC
GVA_INDUSTRY
GVA_SERVICES
GVA_PUBLIC
 GVA_TOTAL
TAXES
GDP
GDP_CAPITA
IDHM
ALT
AREA
GVA_AGROPEC
GVA_INDUSTRY
GVA_SERVICES
GVA_PUBLIC
 GVA_TOTAL
TAXES
GDP
GDP_CAPITA

C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i] = x_train[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].astype(float)
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].str.replace(',', '')
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\971463563.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i] = x_test[i].astype(float)

In [157]:
from sklearn.tree import DecisionTreeClassifier

In [158]:
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

result = model.predict(x_test)
df.CATEGORIA_TUR[df['CATEGORIA_TUR'].isnull()] = result

C:\Users\leona\AppData\Local\Temp\ipykernel_5320\3853482229.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.CATEGORIA_TUR[df['CATEGORIA_TUR'].isnull()] = result
C:\Users\leona\AppData\Local\Temp\ipykernel_5320\3853482229.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.CATEGORIA_TUR[df['CATEGORIA_TUR'].isnull()] = result

In [159]:
encode_tur = pd.get_dummies(df['CATEGORIA_TUR'])
encode_tur = encode_tur.astype(int)
df = pd.concat([df, encode_tur], axis=1)
df.drop(columns=['CATEGORIA_TUR'], axis=1, inplace=True)

In [160]:
for i in df.columns:
    if df[i].dtype == object:
        print(i)
        df[i] = df[i].str.replace(',', '')
        df[i] = df[i].astype(float)

IDHM
ALT
AREA
GVA_AGROPEC
GVA_INDUSTRY
GVA_SERVICES
GVA_PUBLIC
 GVA_TOTAL
TAXES
GDP
GDP_CAPITA

MODEL

In [161]:
x = df.drop('IDHM', axis=1)
y = df['IDHM']

In [162]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score, StratifiedKFold

In [165]:
model = RandomForestRegressor(n_estimators=50)
result = cross_val_score(model, x, y, n_jobs=-1)

print(f'The score of this model was: {result.mean()}')

The score of this model was: 0.8689712902832181